### ISSUE TITLE
Making song request use a command rather than raw link

### ISSUE THREAD

**Issue by ItsCharaHere** [Quaver/Encore#2]
Making the quaver request bot look for !qsr (Quaver Song Request) along with a quaver link to signify its a request, making a command seperate actual discussion of a map rather than an actual request, aswell as the request being ignored by TTS bots, usually ignoring messages that start with !, aswell add a config where the bot can start with ! "message" to be ignored by tts.

**Comment by Benjaminfks** [comment]
Yes Please

**Comment by AiAe** [comment]
Added `!help` and `!r link` as commands
